### ISSUE TITLE
Consider using e.g. VS2022 Test adaptor compatible unit tests

### ISSUE THREAD

**Issue by GeorgeS2019** [PattyHoswell/Godot-NET-Typed-Dictionary#1]
using the [latest](https://github.com/MikeSchulze/gdUnit4Mono/pull/37) gdUnit4API **TestAdaptor** on VS2022

![Z0nhScGr3J](https://github.com/MikeSchulze/gdUnit4Mono/assets/49812372/7d2ed607-0750-4b6e-80f7-e5913aec040e)

**Comment by PattyHoswell** [comment]
What is the benefit from using this test.

I'm sorry if I'm not understanding you correctly. This is my first time using github issue reporting.

**Comment by GeorgeS2019** [comment]
You have written tests.

Imagine using these tests from within VS2022

Your contributors could add more tests to understand you motivation of doing this project

**Comment by PattyHoswell** [comment]
I am using VS2022. And I can see your point but this plugin only make the editor to show the assigned type on the dictionary.

**Comment by PattyHoswell** [comment]
Anyways since this plugin is only viewable from the editor, its not gonna benefit from using this. Thanks for the suggestion though.
